/**
 * Created by Administrator on 2017/9/22.
 */
let jobData = {
      option1:[
        {
          optionName:'私立医院',
          check:false,
          type:0,
        },{
          optionName:'公立医院',
          check:false,
          type:0,
        }
      ],
      option2:[,{
          optionName:'A轮',
          check:false,
          type:0,
      },{
          optionName:'B轮',
          check:false,
          type:0,
      },{
          optionName:'C轮',
          check:false,
          type:0,
      },{
          optionName:'D轮及以上',
          check:false,
          type:0,
      },{
          optionName:'已上市',
          check:false,
          type:0,
      },{
          optionName:'不需要融资',
          check:false,
          type:0,
      },
      {
        optionName:'0-20人',
        check:false,
        type:1,
      },{
        optionName:'20-99人',
        check:false,
        type:1,
      },{
        optionName:'100-499人',
        check:false,
        type:1,
      },{
        optionName:'500-999人',
        check:false,
        type:1,
      },{
        optionName:'1000-9999人',
        check:false,
        type:1,
      },{
        optionName:'10000人以上',
        check:false,
        type:1,
      }
      ],
      option3:[
      {
        optionName:'北京',
        check:false,
        type:2,
      },{
        optionName:'上海',
        check:false,
        type:2,
      },{
        optionName:'淮南',
        check:false,
        type:2,
      },{
        optionName:'郑州',
        check:false,
        type:2,
      },{
        optionName:'合肥',
        check:false,
        type:2,
      },{
        optionName:'武汉',
        check:false,
        type:2,
      },{
        optionName:'长沙',
        check:false,
        type:2,
      },{
        optionName:'成都',
        check:false,
        type:2,
      }
  ]
};
export  {jobData}   /*倒出数据，引入时候使用import {jobData}*/
